name: Testing out vars

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2      
       
      - name: github runner options
        run: echo ${{ github.run_id }}
        
      - name: github runner options
        run: echo ${{ github.run_id }} && echo $GITHUB_WORKSPACE && echo $GITHUB_ACTION_REPOSITORY
        
      - name: Check Git Variable
        run: pwd && ls -R $GITHUB_WORKSPACE && ls -R $GITHUB_ACTION_REPOSITORY
        
